### ISSUE TITLE
Clarify code requirements on "dnd-character"

### ISSUE THREAD

**Issue by MMachado05** [exercism/java#2334] opened 2023-08-12 18:17 UTC
I found myself having to decipher the tests in order to understand what the code I was writing was meant to do. The INSTRUCTIONS.md file for this exercise should have much clearer instructions on the purposes of each method in the included class.

**Comment by Zhreyu** [comment] 2023-10-09 16:46
I would like to take on this issue

**Comment by manumafe98** [comment] 2023-12-21 17:07
Hi! do you guys mind if I take on this issue? 
Reading the previous PR I guess could be great to create a separate `introduction.md` from the `instructions.md` and a `instructions.append.md` to make some notes to clarify that the value should be calculated ones as a hint on using constructors.

**Comment by MMachado05** [comment] 2023-12-22 22:06
@manumafe98 please do! I honestly forgot I'd made it.

**Comment by manumafe98** [comment] 2023-12-22 22:21
@sanderploegsma Please assign it to me when you can! Thanks

**Comment by sanderploegsma** [comment] 2023-12-24 07:42
> Hi! do you guys mind if I take on this issue? 
> 
> Reading the previous PR I guess could be great to create a separate `introduction.md` from the `instructions.md` and a `instructions.append.md` to make some notes to clarify that the value should be calculated ones as a hint on using constructors.

Sure thing! I assigned it to you.

If you can take my feedback on the other PRs into account while working on this, I'm sure you can come up with a viable solution 👍

**Comment by sanderploegsma** [comment] 2023-12-27 14:19
One thing that I would like to respond to is this:

> I found myself having to decipher the tests in order to understand what the code I was writing was meant to do.

This is feedback we often get from students, and usually we try to point out that to an extent this is by design. Practice exercises on Exercism promote Test-Driven Development, which means that sometimes you _should_ look at the tests to see what is expected from the implementation.

So, although I would agree that for this specific exercise the instructions are a little bit terse and _some_ extra information could be useful for students to understand what is required from them, I do not necessarily agree with this statement:

> The INSTRUCTIONS.md file for this exercise should have much clearer instructions on the purposes of each method in the included class.

**Comment by manumafe98** [comment] 2024-02-28 13:51
After the discussion with @sanderploegsma in the following [PR](https://github.com/exercism/java/pull/2603) we decided to not take action on the following issue, we think that the changes on the exercise are minimal and that the current exercise encourages the students to look the tests cases to solve it, which is ok! as this exercise isn't a concept exercise, with those we want to be more clear and concise with the guidance to the students

**Closed by manumafe98** 2024-02-28 13:51 UTC
Labels: x:status/claimed, x:rep/small
